"""Added structures to races

Revision ID: 79f6674fb129
Revises: be620f1a28c1
Create Date: 2024-08-12 18:05:11.872992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from formula_1.db import types as custom_types


# revision identifiers, used by Alembic.
revision: str = '79f6674fb129'
down_revision: Union[str, None] = 'be620f1a28c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', custom_types.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_circuits'))
    )
    op.create_table('constructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', custom_types.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_constructors'))
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', custom_types.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers'))
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('created_at', custom_types.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons'))
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('created_at', custom_types.TZDateTime(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], name=op.f('fk_races_circuit_id_circuits')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_races_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_races'))
    )
    op.create_index(op.f('ix_races_circuit_id'), 'races', ['circuit_id'], unique=False)
    op.create_index(op.f('ix_races_season_id'), 'races', ['season_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_races_season_id'), table_name='races')
    op.drop_index(op.f('ix_races_circuit_id'), table_name='races')
    op.drop_table('races')
    op.drop_table('seasons')
    op.drop_table('drivers')
    op.drop_table('constructors')
    op.drop_table('circuits')
    # ### end Alembic commands ###
