"""Added Formula 1 structs

Revision ID: 6cc21f181509
Revises: be620f1a28c1
Create Date: 2024-08-14 16:27:36.655753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from formula_1.db import types as custom_types


# revision identifiers, used by Alembic.
revision: str = '6cc21f181509'
down_revision: Union[str, None] = 'be620f1a28c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', custom_types.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_circuits'))
    )
    op.create_table('constructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', custom_types.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_constructors'))
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', custom_types.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers'))
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('created_at', custom_types.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons'))
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', custom_types.TZDateTime(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], name=op.f('fk_races_circuit_id_circuits')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_races_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_races'))
    )
    op.create_index(op.f('ix_races_circuit_id'), 'races', ['circuit_id'], unique=False)
    op.create_index(op.f('ix_races_season_id'), 'races', ['season_id'], unique=False)
    op.create_table('race_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('time_in_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], name=op.f('fk_race_positions_constructor_id_constructors')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_race_positions_driver_id_drivers')),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_race_positions_race_id_races')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_positions'))
    )
    op.create_index(op.f('ix_race_positions_constructor_id'), 'race_positions', ['constructor_id'], unique=False)
    op.create_index(op.f('ix_race_positions_driver_id'), 'race_positions', ['driver_id'], unique=False)
    op.create_index(op.f('ix_race_positions_race_id'), 'race_positions', ['race_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_race_positions_race_id'), table_name='race_positions')
    op.drop_index(op.f('ix_race_positions_driver_id'), table_name='race_positions')
    op.drop_index(op.f('ix_race_positions_constructor_id'), table_name='race_positions')
    op.drop_table('race_positions')
    op.drop_index(op.f('ix_races_season_id'), table_name='races')
    op.drop_index(op.f('ix_races_circuit_id'), table_name='races')
    op.drop_table('races')
    op.drop_table('seasons')
    op.drop_table('drivers')
    op.drop_table('constructors')
    op.drop_table('circuits')
    # ### end Alembic commands ###
